coverage:
  precision: 1
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: true
  # Don't display the large graph
  layout: "diff, files"