version: "3"

services:
  ixmp4_server:
    image: registry.iiasa.ac.at/ixmp4/ixmp4-server:dev
    command:
      - ixmp4
      - server
      - start
      - --host=0.0.0.0
    build: ..
    volumes:
      - ./run:/opt/ixmp4/run
    env_file:
      - ./.env
    deploy:
      mode: replicated
      replicas: 4
    ports:
      - 9000-9003:9000
