# type: ignore
"""add ON DELETE CASCADE to timeseries table

Revision ID: 07c169c7792d
Revises: 97ba231770e2
Create Date: 2024-03-06 09:45:00.725366

"""
from alembic import op

# Revision identifiers, used by Alembic.
revision = "07c169c7792d"
down_revision = "97ba231770e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iamc_datapoint_universal", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_iamc_datapoint_universal_time_series__id_iamc_timeseries",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_iamc_datapoint_universal_time_series__id_iamc_timeseries"),
            "iamc_timeseries",
            ["time_series__id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iamc_datapoint_universal", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_iamc_datapoint_universal_time_series__id_iamc_timeseries"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_iamc_datapoint_universal_time_series__id_iamc_timeseries",
            "iamc_timeseries",
            ["time_series__id"],
            ["id"],
        )

    # ### end Alembic commands ###
