# type: ignore
"""Add is_input to datapoints for ixmp-compatibility

Revision ID: 7249db940bf7
Revises: 9596778a8150
Create Date: 2025-10-29 18:45:46.789321

"""

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision = "7249db940bf7"
down_revision = "9596778a8150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iamc_datapoint_universal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_input", sa.Boolean(), nullable=True))

    with op.batch_alter_table(
        "iamc_datapoint_universal_version", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("is_input", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "iamc_datapoint_universal_version", schema=None
    ) as batch_op:
        batch_op.drop_column("is_input")

    with op.batch_alter_table("iamc_datapoint_universal", schema=None) as batch_op:
        batch_op.drop_column("is_input")

    # ### end Alembic commands ###
