# type: ignore
"""Rename opt_idx._data_type column to data_type

Revision ID: 8b0797ebf42f
Revises: 9596778a8150
Create Date: 2025-11-25 15:15:58.112128

"""

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision = "8b0797ebf42f"
down_revision = "9596778a8150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opt_idx", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data_type", sa.String(length=63), nullable=True))
        batch_op.drop_column("_data_type")

    with op.batch_alter_table("opt_idx_version", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data_type", sa.String(length=63), nullable=True))
        batch_op.drop_column("_data_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opt_idx_version", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("_data_type", sa.VARCHAR(length=5), nullable=True)
        )
        batch_op.drop_column("data_type")

    with op.batch_alter_table("opt_idx", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("_data_type", sa.VARCHAR(length=5), nullable=True)
        )
        batch_op.drop_column("data_type")

    # ### end Alembic commands ###
